# Generated by Django 5.1.5 on 2025-10-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0002_conversacion_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='leido',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['conversacion', '-created_at'], name='rentapp_men_convers_8e5c54_idx'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['conversacion', 'leido'], name='rentapp_men_convers_a1ca15_idx'),
        ),
    ]
