# Generated by Django 5.1.5 on 2025-10-21 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0003_alter_mensaje_created_at_alter_mensaje_leido_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversacion',
            unique_together={('participante1', 'participante2', 'local')},
        ),
    ]
